---

name: Reusable CI
on:
  workflow_call:
    secrets:
      REAL_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run echo REAL_TOKEN
        run: echo ${{ secrets.REAL_TOKEN }}
