---

name: Reusable CI
on:
  workflow_call:
    secrets:
      MASTER_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run echo MASTER_TOKEN
        run: echo ${{ secrets.MASTER_TOKEN }}
